server:
  port: 8086

spring:
  application:
    name: incident-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/platform_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

log-parser:
  base-url: ${LOG_PARSER_BASE_URL:http://log-parser-service:5000}

ai-engine:
  base-url: ${AI_ENGINE_BASE_URL:http://ai-engine:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
