server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/platform_db}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:admin}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
