server.port=8084
spring.application.name=log-generator-service

batch.schedule.fixed-rate-ms=${BATCH_SCHEDULE_FIXED_RATE_MS:120000}
batch.schedule.initial-delay-ms=${BATCH_SCHEDULE_INITIAL_DELAY_MS:60000}
services.user.base-url=${USER_SERVICE_URL:http://user-service:8081/api/users}
services.transaction.base-url=${TRANSACTION_SERVICE_URL:http://transaction-service:8082/api/transactions}
services.payment.base-url=${PAYMENT_SERVICE_URL:http://payment-service:8083/api/payments}

management.endpoints.web.exposure.include=health,info,prometheus
