apiVersion: 1

policies:
  - orgId: 1
    receiver: Incident Service Webhook
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: Incident Service Webhook
        object_matchers:
          - [team, =, incident-service]
