name: Banking CI Pipeline

on:
  push:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - Checkout
      - Setup Java
      - Build Common Library
      - Build Services

  test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - Run Tests

  sonar:
    name: SonarQube Analysis
    needs: test
    runs-on: ubuntu-latest
    steps:
      - Sonar Scan

  docker:
    name: Docker Build
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - Build Docker Images

  deploy:
    name: Deploy
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - Deploy to AWS